### ISSUE TITLE
Variable On Owner

### ISSUE THREAD

**Issue by quochung-cyou** [MC-Models/mcpets#8]
What i tried:

- message{m="<target.uuid>"} @PetOwner 

It will return the uuid of pet owner, but somehow it will throw error/ not return anything if player is in Creative Mode (Adventure/Survival work fine)

Server version: Tried 1.16.5/1.18
McPets: 1.0.4
MythicMobs: 5.0.4

**Comment by AlexandreChaussard** [comment]
Hi, I'll be trying this anytime soon, thanks for the feedback
